# Generated by Django 4.2.20 on 2025-05-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hra',
            fields=[
                ('id_Hra', models.AutoField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=45)),
                ('rok_vydani', models.IntegerField()),
                ('cena', models.IntegerField()),
                ('popis', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Hra_has_platforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hra_id_Hra', models.IntegerField()),
                ('Platforma_id_Platforma', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hra_has_zanr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hra_id_Hra', models.IntegerField()),
                ('Zanr_id_Zanr', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hrac',
            fields=[
                ('id_Hrac', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Knihovna_hrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hra_id_Hra', models.IntegerField()),
                ('Hrac_id_Hrac', models.IntegerField()),
                ('datum_ziskani', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Platforma',
            fields=[
                ('id_Platforma', models.AutoField(primary_key=True, serialize=False)),
                ('nazev_platformy', models.CharField(max_length=45)),
            ],
        ),
    ]
