# Generated by Django 5.2 on 2025-06-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='game_photos/', verbose_name='Game Photo'),
        ),
    ]
