# Generated by Django 5.2 on 2025-06-12 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_game_gamegenre_gameplatform_genre_platform_player_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['title'], 'verbose_name': 'Hra', 'verbose_name_plural': 'Hry'},
        ),
        migrations.AlterModelOptions(
            name='gamegenre',
            options={'verbose_name': 'Žánr hry', 'verbose_name_plural': 'Žánry her'},
        ),
        migrations.AlterModelOptions(
            name='gameplatform',
            options={'verbose_name': 'Dostupnost hry na platformě', 'verbose_name_plural': 'Dostupnosti her'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Žánr', 'verbose_name_plural': 'Žánry'},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'verbose_name': 'Platforma', 'verbose_name_plural': 'Platformy'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['nickname'], 'verbose_name': 'Hráč', 'verbose_name_plural': 'Hráči'},
        ),
        migrations.AlterModelOptions(
            name='playerlibrary',
            options={'verbose_name': 'Knihovna hráče', 'verbose_name_plural': 'Knihovny hráčů'},
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2100)], verbose_name='Rok vydání'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Název hry'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Žánr'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Platforma'),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(max_length=50, unique=True, verbose_name='Přezdívka'),
        ),
        migrations.AlterField(
            model_name='playerlibrary',
            name='acquisition_date',
            field=models.DateField(verbose_name='Datum pořízení'),
        ),
        migrations.AlterUniqueTogether(
            name='gamegenre',
            unique_together={('game', 'genre')},
        ),
        migrations.AlterUniqueTogether(
            name='gameplatform',
            unique_together={('game', 'platform')},
        ),
        migrations.AlterUniqueTogether(
            name='playerlibrary',
            unique_together={('player', 'game')},
        ),
    ]
